### ISSUE TITLE
Weird crash between Create, Botania and this one

### ISSUE THREAD

**Issue by Abalieno** [sussy-syrup/smithees-foundry#29]
I have a crash right at the start menu as soon I updated to the latest version of Botania (435).

Using the previous version of Botania works fine but looking at the longer log I found some problem in this mod:

```
Caused by: java.lang.NullPointerException: Cannot invoke "com.sussysyrup.smitheesfoundry.api.recipe.ApiToolRecipe.getKey()" because "recipe" is null
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.method_7854(ToolItem.java:157) ~[smithees-foundry-1.4.2.jar:?]
	at vazkii.botania.client.model.GunModel.<init>(GunModel.java:59) ~[Botania-1.18.2-435-FABRIC.jar:?]
	at vazkii.botania.client.core.handler.MiscellaneousModels.onModelBake(MiscellaneousModels.java:205) ~[Botania-1.18.2-435-FABRIC.jar:?]
	at net.minecraft.class_1092.handler$cec000$onModelBake(class_1092.java:2535) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18179(class_1092.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18788(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
```

This should be the relevant part.

I mentioned Create because the crash log looked different.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4710()" because "$$6" is null
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at net.minecraft.class_918.method_4010(class_918.java:277)
	at com.simibubi.create.foundation.config.ui.OpenCreateMenuButton.method_25353(OpenCreateMenuButton.java:35)
	at net.minecraft.class_339.method_25359(class_339.java:94)
	at net.minecraft.class_4185.method_25359(class_4185.java:45)
	at net.minecraft.class_339.method_25394(class_339.java:67)
	at net.minecraft.class_437.method_25394(class_437.java:109)
	at net.minecraft.class_442.method_25394(class_442.java:345)
	at net.minecraft.class_425.method_25394(class_425.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```

but it still refers to this mod and Botania, so the conflict is between these two.

**Comment by sussy-syrup** [comment]
I have absolutely no idea as to why botania's mana blaster model calls to appendStacks (to assumingly all items) but a null check should fix this specific issue

**Comment by Abalieno** [comment]
I tested it and it seems working now.
