### ISSUE TITLE
Crash when repairing stone smithies axe

### ISSUE THREAD

**Issue by WardsParadox** [sussy-syrup/smithees-foundry#36]
```
[23:24:18] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "com.sussysyrup.smitheesfoundry.api.material.Material.getTraits(String)" because "material" is null
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStackTraits(ToolUtil.java:74) ~[smithees-foundry-1.5.1.1.jar:?]
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStatsTraits(ToolUtil.java:108) ~[smithees-foundry-1.5.1.1.jar:?]
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.getMaxDurability(ToolItem.java:449) ~[smithees-foundry-1.5.1.1.jar:?]
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.method_31567(ToolItem.java:290) ~[smithees-foundry-1.5.1.1.jar:?]
	at net.minecraft.class_1799.method_31578(class_1799.java:368) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4022(class_918.java:385) ~[client-intermediary.jar:?]
	at lol.bai.megane.runtime.util.MeganeUtils.drawStack(MeganeUtils.java:154) ~[megane-runtime-7.9.0-46e0d2a2f692e300.jar:?]
	at lol.bai.megane.runtime.component.InventoryComponent.render(InventoryComponent.java:78) ~[megane-runtime-7.9.0-46e0d2a2f692e300.jar:?]
	at mcp.mobius.waila.util.DisplayUtil.renderComponent(DisplayUtil.java:74) ~[wthit-fabric-4.13.3.jar:?]
	at mcp.mobius.waila.gui.hud.Line.render(Line.java:102) ~[wthit-fabric-4.13.3.jar:?]
	at mcp.mobius.waila.gui.hud.TooltipRenderer.render(TooltipRenderer.java:248) ~[wthit-fabric-4.13.3.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-1.10.7+54e5b2ec60-fd4a2ad05dc25f68.jar:?]
	at net.minecraft.class_329.handler$bmj000$render(class_329.java:4029) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:415) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:858) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[23:24:18] [Render thread/INFO]: Minimap session finalized.
[23:24:18] [Render thread/INFO]: Finalizing world map session...
[23:24:18] [Thread-20/INFO]: World map force-cleaned!
[23:24:18] [Render thread/INFO]: World map session finalized.
[23:24:18] [Render thread/INFO]: Stopping worker threads
---- Minecraft Crash Report ----
// There are four lights!
Time: 9/25/22, 11:24 PM
Description: Unexpected error
java.lang.NullPointerException: Cannot invoke "com.sussysyrup.smitheesfoundry.api.material.Material.getTraits(String)" because "material" is null
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStackTraits(ToolUtil.java:74)
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStatsTraits(ToolUtil.java:108)
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.getMaxDurability(ToolItem.java:449)
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.method_31567(ToolItem.java:290)
	at net.minecraft.class_1799.method_31578(class_1799.java:368)
	at net.minecraft.class_918.method_4022(class_918.java:385)
	at lol.bai.megane.runtime.util.MeganeUtils.drawStack(MeganeUtils.java:154)
	at lol.bai.megane.runtime.component.InventoryComponent.render(InventoryComponent.java:78)
	at mcp.mobius.waila.util.DisplayUtil.renderComponent(DisplayUtil.java:74)
	at mcp.mobius.waila.gui.hud.Line.render(Line.java:102)
	at mcp.mobius.waila.gui.hud.TooltipRenderer.render(TooltipRenderer.java:248)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bmj000$render(class_329.java:4029)
	at net.minecraft.class_329.method_1753(class_329.java:415)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStackTraits(ToolUtil.java:74)
	at com.sussysyrup.smitheesfoundry.util.ToolUtil.getStatsTraits(ToolUtil.java:108)
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.getMaxDurability(ToolItem.java:449)
	at com.sussysyrup.smitheesfoundry.api.item.ToolItem.method_31567(ToolItem.java:290)
	at net.minecraft.class_1799.method_31578(class_1799.java:368)
	at net.minecraft.class_918.method_4022(class_918.java:385)
	at lol.bai.megane.runtime.util.MeganeUtils.drawStack(MeganeUtils.java:154)
	at lol.bai.megane.runtime.component.InventoryComponent.render(InventoryComponent.java:78)
	at mcp.mobius.waila.util.DisplayUtil.renderComponent(DisplayUtil.java:74)
	at mcp.mobius.waila.gui.hud.Line.render(Line.java:102)
	at mcp.mobius.waila.gui.hud.TooltipRenderer.render(TooltipRenderer.java:248)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bmj000$render(class_329.java:4029)
	at net.minecraft.class_329.method_1753(class_329.java:415)
-- Affected level --
Details:
	All players: 1 total; [class_746['WardsParadox'/14025, l='ClientLevel', x=-6265.18, y=88.00, z=-3778.83]]
	Chunk stats: 1024, 470
	Level dimension: minecraft:overworld
	Level spawn location: World: (-6150,73,-3697), Section: (at 10,9,15 in -385,4,-232; chunk contains blocks -6160,-64,-3712 to -6145,319,-3697), Region: (-13,-8; contains chunks -416,-256 to -385,-225, blocks -6656,-64,-4096 to -6145,319,-3585)
	Level time: 153350 game time, 79919 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Faithful 32x - 1.19.2.zip, goat-horns-plus-32x.zip, wall-e1290.zip, 3D Glass Doors.zip, Create Legacy Copper, 3D Ladders.zip, Better Redstone Ore C32x.zip, Custom Paintings 1.16.2.zip, Faithful-Java-32x-Better_Observers_v1.0.zip, Faithful-Java-32x-Directional_Droppers+Dispensers_v1.0.zip, Faithful-Java-32x-Directional_Hopper+Bottom_Fix_v1.0.zip, Faithful-Java-32x-Sticky_Piston_Sides_v1.0.zip, Faithful-Java-32x-Visual_Honey_Stages_v1.0.zip, Long Hotbar - 32x.zip, LowerFire+[1.18.x].zip, Rainbow XP Bar 32x.zip, Redstone+Utilities-v2+[1.18.x].zip, Visual-Maps-Compliance-32x.zip, bannerpatterns.zip, blast-furnace-front-fix-32x.zip, book-e2110.zip, bottle-3d-e1290.zip
-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4.1, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 1939396904 bytes (1849 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 34748.05
	Virtual memory used (MB): 17852.32
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 109.18
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	Fabric Mods: 
		ae2: Applied Energistics 2 11.2.0
			noindium: No Indium? 1.0.2+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
			team_reborn_energy: Energy 2.0.0-beta1
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architectury: Architectury 4.9.84
		badpackets: Bad Packets 0.1.2
		beaconoverhaul: Beacon Overhaul 1.6.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.10+0d9ab37260
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v6 6.3.81
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.68
			fiber: fiber 0.23.0-2
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		create: Create 0.5.0d-731
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.4-30
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.4
		durabilityviewer: Giselbaers Durability Viewer 1.18.2-fabric0.47.10-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
			gbfabrictools: GBfabrictools 1.3.4+1.18.2
		easiercrafting: EasierCrafting 1.18.2-fabric0.47.10-1.7
		easiervillagertrading: EasierVillagerTrading 1.18.2-fabric0.47.10-1.5.4
		fabric-api: Fabric API 0.59.0+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.1+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.3+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fabrikmc-all: FabrikMC (All modules) 1.7.4
			fabrikmc-commands: FabrikMC Commands 1.7.4
			fabrikmc-compose: FabrikMC Compose 1.7.4
				com_github_ajalt_colormath_colormath-jvm: colormath-jvm 3.2.0
				net_axay_fabrikmc-compose-mojang-api_: fabrikmc-compose-mojang-api 1.7.4
				org_apache_commons_commons-csv: commons-csv 1.9.0
				org_jetbrains_compose_animation_animation-core-desktop: animation-core-desktop 1.0.1
				org_jetbrains_compose_animation_animation-desktop: animation-desktop 1.0.1
				org_jetbrains_compose_desktop_desktop-jvm: desktop-jvm 1.0.1
				org_jetbrains_compose_foundation_foundation-desktop: foundation-desktop 1.0.1
				org_jetbrains_compose_foundation_foundation-layout-desktop: foundation-layout-desktop 1.0.1
				org_jetbrains_compose_material_material-desktop: material-desktop 1.0.1
				org_jetbrains_compose_material_material-icons-core-desktop: material-icons-core-desktop 1.0.1
				org_jetbrains_compose_material_material-ripple-desktop: material-ripple-desktop 1.0.1
				org_jetbrains_compose_runtime_runtime-desktop: runtime-desktop 1.0.1
				org_jetbrains_compose_runtime_runtime-saveable-desktop: runtime-saveable-desktop 1.0.1
				org_jetbrains_compose_ui_ui-desktop: ui-desktop 1.0.1
				org_jetbrains_compose_ui_ui-geometry-desktop: ui-geometry-desktop 1.0.1
				org_jetbrains_compose_ui_ui-graphics-desktop: ui-graphics-desktop 1.0.1
				org_jetbrains_compose_ui_ui-text-desktop: ui-text-desktop 1.0.1
				org_jetbrains_compose_ui_ui-tooling-preview-desktop: ui-tooling-preview-desktop 1.0.1
				org_jetbrains_compose_ui_ui-unit-desktop: ui-unit-desktop 1.0.1
				org_jetbrains_compose_ui_ui-util-desktop: ui-util-desktop 1.0.1
				org_jetbrains_kotlinx_kotlinx-coroutines-swing: kotlinx-coroutines-swing 1.5.2
				org_jetbrains_kotlinx_multik-api: multik-api 0.1.1
				org_jetbrains_kotlinx_multik-jvm: multik-jvm 0.1.1
				org_jetbrains_skiko_skiko-jvm: skiko-jvm 0.6.6
				org_jetbrains_skiko_skiko-jvm-runtime-linux-arm64: skiko-jvm-runtime-linux-arm64 0.6.6
				org_jetbrains_skiko_skiko-jvm-runtime-linux-x64: skiko-jvm-runtime-linux-x64 0.6.6
				org_jetbrains_skiko_skiko-jvm-runtime-macos-arm64: skiko-jvm-runtime-macos-arm64 0.6.6
				org_jetbrains_skiko_skiko-jvm-runtime-macos-x64: skiko-jvm-runtime-macos-x64 0.6.6
				org_jetbrains_skiko_skiko-jvm-runtime-windows-x64: skiko-jvm-runtime-windows-x64 0.6.6
			fabrikmc-core: FabrikMC Core 1.7.4
			fabrikmc-game: FabrikMC Game 1.7.4
			fabrikmc-igui: FabrikMC Inventory GUI 1.7.4
			fabrikmc-nbt: FabrikMC NBT 1.7.4
			fabrikmc-network: FabrikMC Network 1.7.4
			fabrikmc-persistence: FabrikMC Persistence 1.7.4
		ferritecore: FerriteCore 4.2.1
		flytre_lib: FlytreLib 1.8.2
		harvest_scythes: Harvest Scythes 2.5.1
			mm: Manningham Mills 2.3
		healthoverlay: Health Overlay 6.3.4
		indium: Indium 1.0.7+mc1.18.2
		indrev: Industrial Revolution 1.14.0-BETA
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
			magna: Magna 1.7.0-1.18-pre1
			patchouli: Patchouli 1.18.2-66-FABRIC
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		inventorymanagement: Inventory Management 1.0.3
		java: OpenJDK 64-Bit Server VM 17
		kibe: Kibe 1.9.9-BETA+1.18
			playerabilitylib: Pal 1.5.0
		lighty: Lighty 1.0.4
		mcwbridges: Macaw's Bridges 2.0.4
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwroofs: Macaw's Roofs 2.2.0b
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 7.9.0
			megane-api: megane-api 7.9.0
			megane-applied-energistics-2: megane-applied-energistics-2 7.9.0
			megane-create: megane-create 7.9.0
			megane-fabric-transfer: megane-fabric-transfer 7.9.0
			megane-industrial-revolution: megane-industrial-revolution 7.9.0
			megane-kibe: megane-kibe 7.9.0
			megane-lib-block-attributes: megane-lib-block-attributes 7.9.0
			megane-reborn-energy: megane-reborn-energy 7.9.0
			megane-runtime: megane-runtime 7.9.0
			megane-vanilla: megane-vanilla 7.9.0
		microdurability: microDurability 0.3.6+1.17
			microdurability-core: microDurability Core 0.3.6
		minecraft: Minecraft 1.18.2
		mobcapturingtool: Mob Capturing Tool 1.0.1
		modmenu: Mod Menu 3.2.3
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		neat: Neat 1.8-31-FABRIC
		phosphor: Phosphor 0.8.1
		relative-xp: Relative XP 1.0.0
		roughlyenoughitems: Roughly Enough Items 8.3.545
			error_notifier: Error Notifier 1.0.9
		simplechunkloader: Simple Chunkloader 1.0.1
			libgui: LibGui 5.4.0+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		smitheesfoundry: Smithee's Foundry 1.5.1.1
			smcompat: Smithee's Foundry Compat 1.1.1
			sussyconfig: Sussy Config 1.0.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		terrestria: Terrestria 4.0.3
			terrablender: TerraBlender 1.1.0.102
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 3.1.0
			terraform-config-api-v1: Terraform Config API (v1) 3.1.0
			terraform-dirt-api-v1: Terraform Dirt API (v1) 3.1.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 3.1.0
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 3.1.0
			terraform-tree-api-v1: Terraform Tree API (v1) 3.1.0
			terraform-wood-api-v1: Terraform Wood API (v1) 3.1.0
			terrestria-client: Terrestria: Client 4.0.3
			terrestria-common: Terrestria: Common 4.0.3
			terrestria-worldgen: Terrestria: World Generation 4.0.3
		traverse: Traverse 5.1.4
			traverse-client: Traverse: Client 5.1.4
			traverse-common: Traverse: Common 5.1.4
			traverse-worldgen: Traverse: World Generation 5.1.4
		treeharvester-fabric: Tree Harvester (Fabric) 5.7
		trinkets: Trinkets 3.3.1
			cardinal-components-base: Cardinal Components API (base) 4.1.3
			cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		waig: Where Am I Going 1.1.3
		wthit: wthit 4.13.3
		xaerominimap: Xaero's Minimap 22.14.1
		xaeroworldmap: Xaero's World Map 1.27.0
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Faithful 32x - 1.19.2.zip (incompatible), file/goat-horns-plus-32x.zip (incompatible), file/wall-e1290.zip, file/3D Glass Doors.zip (incompatible), Create Legacy Copper, file/3D Ladders.zip (incompatible), file/Better Redstone Ore C32x.zip (incompatible), file/Custom Paintings 1.16.2.zip (incompatible), file/Faithful-Java-32x-Better_Observers_v1.0.zip, file/Faithful-Java-32x-Directional_Droppers+Dispensers_v1.0.zip, file/Faithful-Java-32x-Directional_Hopper+Bottom_Fix_v1.0.zip, file/Faithful-Java-32x-Sticky_Piston_Sides_v1.0.zip, file/Faithful-Java-32x-Visual_Honey_Stages_v1.0.zip, file/Long Hotbar - 32x.zip (incompatible), file/LowerFire+[1.18.x].zip, file/Rainbow XP Bar 32x.zip (incompatible), file/Redstone+Utilities-v2+[1.18.x].zip, file/Visual-Maps-Compliance-32x.zip, file/bannerpatterns.zip (incompatible), file/blast-furnace-front-fix-32x.zip, file/book-e2110.zip, file/bottle-3d-e1290.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\zackm\AppData\Roaming\PolyMC\instances\1.18.2\.minecraft\crash-reports\crash-2022-09-25_23.24.19-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by sussy-syrup** [comment]
Thanks, I will try to fix this this weekend. Sorry for the wait I am just very busy with uni right now

**Comment by WardsParadox** [comment]
No worries, totally understand. Just noticed it and reporting :)

**Comment by sussy-syrup** [comment]
Right I cannot replicate this with just the mod alone which means that this is mod interaction going bad. I will try to find a fix

**Comment by sussy-syrup** [comment]
This should fix it. It definitely shouldn't crash, let me know if it ends up doing something weird
